language: php

php:
  - 7.2

before_script:
  - cp config/config.Example.php config/config.php
  - composer self-update
  - composer install --no-interaction

script:  ./vendor/bin/phpunit tests

cache:
  directories:
    - vendor